# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(304, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GBimageProcessing = QtWidgets.QGroupBox(self.centralwidget)
        self.GBimageProcessing.setGeometry(QtCore.QRect(10, 10, 281, 301))
        self.GBimageProcessing.setObjectName("GBimageProcessing")
        self.btnShowTrainImages = QtWidgets.QPushButton(self.GBimageProcessing)
        self.btnShowTrainImages.setGeometry(QtCore.QRect(30, 30, 230, 30))
        self.btnShowTrainImages.setStyleSheet("text-align:center;")
        self.btnShowTrainImages.setObjectName("btnShowTrainImages")
        self.btnShowHyperParameter = QtWidgets.QPushButton(self.GBimageProcessing)
        self.btnShowHyperParameter.setGeometry(QtCore.QRect(30, 75, 230, 30))
        self.btnShowHyperParameter.setStyleSheet("text-align:center;")
        self.btnShowHyperParameter.setObjectName("btnShowHyperParameter")
        self.btnShowModelShortcut = QtWidgets.QPushButton(self.GBimageProcessing)
        self.btnShowModelShortcut.setGeometry(QtCore.QRect(30, 120, 230, 30))
        self.btnShowModelShortcut.setStyleSheet("text-align:center;")
        self.btnShowModelShortcut.setObjectName("btnShowModelShortcut")
        self.btnShowAccuracy = QtWidgets.QPushButton(self.GBimageProcessing)
        self.btnShowAccuracy.setGeometry(QtCore.QRect(30, 165, 230, 30))
        self.btnShowAccuracy.setStyleSheet("text-align:center;")
        self.btnShowAccuracy.setObjectName("btnShowAccuracy")
        self.btnTest = QtWidgets.QPushButton(self.GBimageProcessing)
        self.btnTest.setGeometry(QtCore.QRect(30, 255, 230, 30))
        self.btnTest.setStyleSheet("text-align:center;")
        self.btnTest.setObjectName("btnTest")
        self.teChooseData = QtWidgets.QTextEdit(self.GBimageProcessing)
        self.teChooseData.setGeometry(QtCore.QRect(30, 210, 230, 30))
        self.teChooseData.setObjectName("teChooseData")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 304, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GBimageProcessing.setTitle(_translate("MainWindow", "VGG 16 TEST"))
        self.btnShowTrainImages.setText(_translate("MainWindow", "1. Show Train Images"))
        self.btnShowHyperParameter.setText(_translate("MainWindow", "2. Show HyperParameter"))
        self.btnShowModelShortcut.setText(_translate("MainWindow", "3. Show Model Shortcut"))
        self.btnShowAccuracy.setText(_translate("MainWindow", "4. Show Accuracy"))
        self.btnTest.setText(_translate("MainWindow", "5. Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
